#!/bin/bash

N=$(nproc)

if [ -f Makefile ] ; then
	make -j$N clean
fi

for i in `find . -type f -name "*.orig"`; do rm $i; done
for i in `find . -type f -name "*.rej"`; do rm $i; done
for i in `find . -type f -name "*.bak"`; do rm $i; done
